library(testthat);

context("Tests of Dunn-Smyth Residuals")

test_that("Seed argument works for setting final residual computation", {
  a <- cdfvals_2_dsres_discrete(rep(0.5, 6), rep(0.6, 6), seed = 5346)
  b <- cdfvals_2_dsres_discrete(rep(0.5, 6), rep(0.6, 6), seed = 5346)
  c <- cdfvals_2_dsres_discrete(rep(0.5, 6), rep(0.6, 6), seed = NULL)
  d <- cdfvals_2_dsres_discrete(rep(0.5, 6), rep(0.6, 6), seed = NULL)
  expect_identical(a, b)
  expect_false(isTRUE(all.equal(a, c)))
  expect_false(isTRUE(all.equal(c, d)))
  expect_false(isTRUE(all.equal(a, d)))
})

test_that("PDF and CDF computations are correct"){
  expect_equal(hetpdf(0, c(0.1, 0.2)), 0.9 * 0.8)
  expect_equal(hetpdf(2, c(0.1, 0.2)), 0.1 * 0.2)
  expect_equal(hetpdf(1, c(0.1, 0.2)), 1 - 0.9 * 0.8 - 0.1 * 0.2)
  expect_equal(hetpdf(-1, c(0.1, 0.2)), 0)
  expect_equal(hetpdf(1.3, c(0.1, 0.2)), 0)
  expect_equal(hetpdf(3, c(0.1, 0.2)), 0)
  
  expect_equal(hetcdf(0, c(0.1, 0.2)),  0.9 * 0.8)
  expect_equal(hetcdf(1, c(0.1, 0.2)),  1 - 0.1 * 0.2)
  
  pDetected <- runif(5)
  expect_equal(hetcdf(0.3, pDetected),  hetcdf(0, pDetected))
  expect_equal(hetcdf(-0.1, pDetected),  0)
  expect_equal(hetcdf(length(pDetected), pDetected),  1)
  expect_equal(hetcdf(2.1, pDetected),  hetcdf(2, pDetected))
  expect_gt(hetcdf(3, pDetected), hetcdf(2, pDetected))
  
  # compare to simulations
  s <- summary(as.factor(simDetectedDistr(500000, pDetected)))/500000
  p <- vapply(0:length(pDetected), hetpdf, pDetected = pDetected, FUN.VALUE = 3)
  names(p) <- 0:length(pDetected)
  expect_equal(s, p, tolerance = 1E-3)
}

test_that("Detection residuals sensible for simulated data", {
  # simulate a data set
  species <- c("A", "B", "C", "D")
  sites <- c(1:1000)
  occupancy <- expand.grid(Species = species, SiteID = sites)
  occupancy$pOccupancy <- runif(nrow(occupancy))
  
  visits <- rbind(occupancy, occupancy, occupancy[1:(2 * length(species)), ],
                  occupancy, occupancy, occupancy)
  specdet_base <- runif(length(species), 0.2, 0.8)
  names(specdet_base) <- species
  visitdetprob_offset <- runif(nrow(visits), -0.1, 0.1)
  preds <- visits %>%
    dplyr::mutate(pDetected = pOccupancy * (specdet_base[Species] + visitdetprob_offset))
  
  # simulate observations from the given predicted values (purely for testing)
  obs <- preds %>% dplyr::select(Species, SiteID)
  obs$Detected <- mapply(rbinom, prob = preds$pDetected, MoreArgs = list(n = 1, size = 1))

  # test residuals
  expect_equal(ds_detection_residuals(preds, obs, seed = 1234),
               ds_detection_residuals(preds, obs, seed = 1234))
  expect_true(any(ds_detection_residuals(preds, obs) != 
               ds_detection_residuals(preds, obs)))
  
  # residuals should have a standard gaussian distribution when observations generated by model given by preds
  ds_residuals <- ds_detection_residuals(preds, obs)
  shapiroresults <- shapiro.test(ds_residuals)
  expect_gt(shapiroresults$p.value, 0.05) #if things are good this test will fail 1/20 times
})

test_that("Occupancy residuals sensible for simulated data", {
  # simulate a data set
  species <- c("A", "B", "C", "D")
  sites <- c(1:10)
  occupancy <- expand.grid(Species = species, SiteID = sites)
  occupancy$pOccupancy <- runif(nrow(occupancy))
  
  visits <- rbind(occupancy, occupancy, occupancy[1:(2 * length(species)), ],
                  occupancy, occupancy, occupancy)
  specdet_base <- runif(length(species), 0.2, 0.8)
  names(specdet_base) <- species
  visitdetprob_offset <- runif(nrow(visits), -0.1, 0.1)
  preds <- visits %>%
    dplyr::mutate(pDetected = pOccupancy * (specdet_base[Species] + visitdetprob_offset))
  
  # simulate observations from the given predicted values (purely for testing)
  obs <- preds %>% dplyr::select(Species, SiteID)
  obs$Detected <- mapply(rbinom, prob = preds$pDetected, MoreArgs = list(n = 1, size = 1))
  
  # test residuals response to seed
  expect_equal(ds_occupancy_residuals(preds, obs, seed = 1234),
               ds_occupancy_residuals(preds, obs, seed = 1234))
  expect_true(any(ds_occupancy_residuals(preds, obs) != 
                    ds_occupancy_residuals(preds, obs)))
  
  # residuals should have a standard gaussian distribution when observations generated by model given by preds
  ds_residuals <- ds_occupancy_residuals(preds, obs)
  shapiroresults <- shapiro.test(ds_residuals)
  expect_gt(shapiroresults$p.value, 0.05) #if things are good this test will fail 1/20 times
})

test_that("Detection residuals computed for cases where only one species and site", {
  species <- c("A")#, "B", "C", "D")
  sites <- c(1)
  occupancy <- expand.grid(Species = species, SiteID = sites)
  occupancy$pOccupancy <- runif(nrow(occupancy))
  
  visits <- rbind(occupancy, occupancy)
  specdet_base <- runif(length(species), 0.2, 0.8)
  names(specdet_base) <- species
  visitdetprob_offset <- runif(nrow(visits), -0.1, 0.1)
  preds <- visits %>%
    dplyr::mutate(pDetected = pOccupancy * (specdet_base[Species] + visitdetprob_offset))
  
  # simulate observations from the given predicted values (purely for testing)
  obs <- preds %>% dplyr::select(Species, SiteID)
  obs$Detected <- mapply(rbinom, prob = preds$pDetected, MoreArgs = list(n = 1, size = 1))
  
  expect_equal(length(ds_detection_residuals(preds, obs)), nrow(obs))
})
